### ISSUE TITLE
string handling broken

### ISSUE THREAD

**Issue by matu3ba** [Himujjal/tree-sitter-zig#1]
String parsing is somewhat broken as `//` and `\\` are sometimes misinterpreted as multiline strings. Followup regular string "anyword" kinda fixes it for the text thereafter.

Try for yourself in [zls main.zig line 1423](https://github.com/zigtools/zls/blob/3a8d4c7bfb5daeaec5ff55fa8cf39e7fe0f82f9d/src/main.zig#L1424).
```zig
fn signatureHelperHandler(arena: *std.heap.ArenaAllocator, id: types.RequestId, config: Config) !void {
    // TODO Implement this
    try respondGeneric(id,
        \\,"result":{"signatures":[]}}
    );
}
```
The stuff below \\ is recognized as string.

Line 963: the stuff after
```zig
    return std.mem.indexOf(u8, tree.source[start..end], "//") != null;
```
is also recognized as multiline string.

The lines below line 193 also with
```zig
// TODO: Is this correct or can we get a better end?

fn astLocationToRange(loc: std.zig.ast.Tree.Location) types.Range {
    return .{
        .start = .{
            .line = @intCast(i64, loc.line),
            .character = @intCast(i64, loc.column),
        },
        .end = .{
            .line = @intCast(i64, loc.line),
            .character = @intCast(i64, loc.column),
        },
    };
}
```

**Comment by Himujjal** [comment]
Yeah. Its has to be handled by an external scanner. Its a bit of work, but its possible. Please use zig.vim plugin for now if you are using neovim till this is fixed.

Also, throw in all the syntax highlighting issues. I will fix them one by one.

**Comment by matu3ba** [comment]
Again string handling
ast.zig:72, ast.zig:61 has white @s, but @s in line 67,68,70 not. I guess this is the same issue of multiline strings.
Multiline strings are bright green, whereas single line strings are darker green (with white @ in front).

![potential_issue](https://user-images.githubusercontent.com/13089667/112769177-f395d180-901f-11eb-94a0-562285afad87.png)

~~I am not exactly sure, if this is related to zig.vim being active.~~ Nope, unrelated to zig.vim.

The tags should be yellow instead as shown in the following (AST.zig, line 147): 
![difference_tags](https://user-images.githubusercontent.com/13089667/112769319-b1b95b00-9020-11eb-98e4-31dd0f4c3514.png)

**Comment by Himujjal** [comment]
Ah. okay. I have opened another issue for this. I will fix them later. till then use `zig.vim`. There were some indentation issues too. I will try to fix them all.

**Comment by matu3ba** [comment]
Here is another example of wrong tag color in ast.zig line 555. and I am not exactly sure why this happened:

![wrong_tag_color](https://user-images.githubusercontent.com/13089667/112769429-2c827600-9021-11eb-8735-57ac9089c5a8.png)

Tags in line 205, 227, 248, 320, 429 look identical (wrongly colored).

**Comment by matu3ba** [comment]
Maybe more of a nit, but would show proper string handling: The keywords `while, if, continue, switch` are not colored as string even though they are a string in lines 538, 543.
`.@"while"` etc.

I took probably one of the harder examples for the grammar.

**Comment by Himujjal** [comment]
These issues are mostly fixed with the latest commits. As of now, this issue: [nvim-treesitter#839](https://github.com/nvim-treesitter/nvim-treesitter/issues/839) is blocking PR to nvim-treesitter. I have notifications on for this one. Once its fixed, I will push the changes.

Anyways, I will not push to the official nvim-treesitter until all the syntax highlighting works perfectly. BTW, @matu3ba  can you check `corpus/*.txt` files and see if I have a certain case not covered in the tests. Tests are written this way: https://tree-sitter.github.io/tree-sitter/creating-parsers#command-test . If something is missing, please do make a PR. I will write the relevant AST code. Only Zig code will be enough.

**Comment by matu3ba** [comment]
@Himujjal You are missing tokens in the literals. At least in the tests. The highlighting works fine though.
https://github.com/ziglang/zig-spec/blob/master/grammar/grammar.y#L338

It is abit unfortunate that the complete spec is not linked in the documentation.
The following comments are my summary on what stuff to look into. Must sleep due to being kinda sick.

For example integers literals can be arbitrarily separated by `_`:
```zig
1_000
10_00
100_0
0b0_1
0b0_0_1
0b_0_00  //THIS is INVALID
0x0_F
0x0_0_F
0x_0_0F  //THIS is INVALID
```
Floats as well:
```
0_1.1
0_1.12
0_1.1_22
0_1.1_22e+2_2
0_1.1_2E2_2;
0_1.1_2E-2_2;
```

TODOs adjust highlighting to styleguide:
- [ ] Enum literals, struct fields and union fields must be snake_case
- [ ] functions are camelCase with small letter beginning
- [ ] Types are CamelCase with upper letter beginning (this means Variable: enum = ..., Variable: struct  = ..., Variable: union = ...)

Exceptions to this rule should be __HIGHLIGHTED__ IN RED ?

**Comment by matu3ba** [comment]
### Missing tests for Compound Assigment expression:
`*%=`
`-%=`
`+%=`
### Compound Assigment expression:
`~true //this is a binary not operation !!! => error, remove!`

### Binary expression:
`// add all wrapping (%) operations.`

### Type expression:
`!u8`
`c_type` expressions are completely missing => some special cases
`comptime, const` checks
`VarDecl`

### Call expressions (both build in and normal):
`FnProto`

### Reference and deference expression:
`c pointer`, `pointer types?!`, `pointer offset change`, 

### Slice pattern expression
Is there no `[s...end]` (for including end) `?`

### Field expression:

1. file access missing
2. tuple field access missing

### Struct expression:
1. simple nested struct

### Union expression:
// union (enum) example formulated

### Test expression:
1. variable assignment
2. print statement

**Comment by matu3ba** [comment]
### Assigments statements:
likely incomplete: `ctype` stuff for example

### Function declaration statements:
`noinline`, `extern "blabla"`, 

`fn testfn ( params ) ByteAlign? LinkSection? CallConv? EXCLAMATIONMARK? (KEYWORD_anytype / TypeExpr)

### `threadlocal`
```zig
threadlocal var y: i32 = 2; // thread local variable => statements
```

### MISC
`__nakedcc`, `stdcallc __` completely missing from grammar

**Comment by Himujjal** [comment]
woah. thank you so much. i will work on this soon
