### ISSUE TITLE
Intended highlighting of `.variable` unclear

### ISSUE THREAD

**Issue by matu3ba** [Himujjal/tree-sitter-zig#5]
field access with `.variable` on left hand side and field description appear to be identical.
However on `.stack_id = .Paren` only `.stack_id` is highlighted.

What is the intended rule for highlighting here?
Only left hand side? What about nested structures (think of everything is an expression)?

**Comment by Himujjal** [comment]
Can you provide a good example. I am not so well versed with Zig. I simply used the EBNF grammar in official documentation to produce this tree-sitter grammar.

To be it seems only left-side highlighting should be enough. Any strange case you would like to point out?

**Comment by matu3ba** [comment]
TODOs adjust highlighting to styleguide:

1. [ ] Enum literals, struct fields and union fields must be snake_case
2. [ ] functions are camelCase with small letter beginning
3. [ ] Types are CamelCase with upper letter beginning (this means Variable: enum = ..., Variable: struct = ..., Variable: union = ...)
4. [ ] Clarify how non-conforming symbols should be highlighted!

Problem: ZLS is non-conforming to style guide.

**Comment by Himujjal** [comment]
The above is the work of ZLS. I mean syntax highlighting should not interfere in my opinion whether the linting is right or not.

If `zig build` compiles something, then that should be syntax highlighted without error. Whether its non style conforming, that's linter's work.
